api/urls.py
from django.conf.urls import url
from django.urls import path, include

from rest_framework import routers
from user.views import InterestViewSet, UserInterestViewSet
from party.views import PartyViewSet
from . import views

interest_view = InterestViewSet.as_view({
    'post':'create',
    'get':'list'
})

user_interest_view = UserInterestViewSet.as_view({
    'post': 'create',
    'get': 'list'
})

party_view = PartyViewSet.as_view({
    'post': 'create',
    'get': 'list'
})

urlpatterns = [
    path('user/login',views.login),
    

    path('interest/',interest_view),
    path('user_interest/',user_interest_view),
    
    path('party/', party_view)
]

bucket/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from user import views

urlpatterns = [
    path("", views.profile),
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("manager/", include("manager.urls")),
    path("user/", include("user.urls")),
    path("party/", include("party.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from user import social_login
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index),
    path('profile', views.profile, name='profile'),
    path('find_password/', views.find_password, name='find_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('login/', views.login, name='login'),    
    path('update/', views.update, name='update'),    
    path('delete/', views.delete, name='delete'),    
    path('login/<str:type>/', social_login.login_social),
    path('callback/<str:type>/', views.callback_social),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    # path('activate', views.activate),
    path('activate/<uidb64>/<token>/', views.activate,  name='activate'),
    path('reset_password/<uidb64>/<token>/', views.reset_password,  name='reset_password')
]

user/models.py
from django.db import models
import datetime
import os
from django.db.models.base import Model
from django.utils.deconstruct import deconstructible


@deconstructible
class PathAndRename(object):
    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split(".")[-1]
        now = datetime.datetime.now()
        date_time = now.strftime("%y%m%d_%H%M%S")
        filename = "img_user_{}.{}".format(str(date_time), str(ext))
        return os.path.join(self.path, filename)


class User(models.Model):
    name = models.CharField(max_length=32, null=False)
    password = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=128, null=False)
    phone = models.CharField(max_length=11, null=True)
    image = models.ImageField(upload_to=("user/"), default="default_image.jpg")
    detail = models.CharField(max_length=500, null=True)
    social_login = models.CharField(max_length=10, null=True)
    social_id = models.CharField(max_length=200, null=True)
    is_active = models.BooleanField(null=False, default=False)
    is_admin = models.BooleanField(null=False, default=False)
    instagram = models.CharField(max_length=100, null=True)

    class Meta:
        db_table = "user"


class Interest(models.Model):
    interest = models.CharField(max_length=10, unique=True)

    class Meta:
        db_table = "interest"


class UserInterest(models.Model):
    user_id = models.ForeignKey(
        to=User, db_column="user_id", null=False, on_delete=models.CASCADE
    )
    interest_id = models.ForeignKey(
        to=Interest, db_column="interest_id", null=False, on_delete=models.CASCADE
    )

    class Meta:
        db_table = "user_interest"

user/forms.py
from django import forms
from .models import User
from django.contrib.auth.hashers import check_password


class LoginForm(forms.Form):
    username = forms.CharField(
        label="사용자 이름",
        max_length=32, 
        error_messages={'required': '아이디를 입력해주세요.'}
    )
    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput, 
        error_messages={'required': '비밀번호를 입력해주세요.'}
    )
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        image = cleaned_data.get('image')
        if username and password:
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                self.add_error('username', '아이디가 없습니다')
                return
            if not check_password(password, user.password):
                self.add_error('password', 'password: {} user.passwor: {}'.format(password, user.password))
            else:
                self.user_id = user.id

class RegisterForm(forms.Form):
    username = forms.CharField(
        error_messages={'required': '유저명을 입력해주세요.'},
        max_length=64, 
        label='유저명'
    )
    email = forms.CharField(
        error_messages={'required': '이메일'},
        max_length=128, 
        label='이메일'
    )
    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput, 
        error_messages={'required': '비밀번호를 입력해주세요.'}
    )
    re_password = forms.CharField(
        label="비밀번호 확인",
        widget=forms.PasswordInput, 
        error_messages={'required': '비밀번호를 입력해주세요.'}
    )
    # image = forms.ImageField(
    #     error_messages={'required': '이미지를 입력해주세요.'}, 
    #     label='이미지',
    # )
    image = forms.FileField(
        error_messages={'required': '이미지를 입력해주세요.'}, 
        label='이미지!',
        widget=forms.FileInput(attrs={'accept':'image/*,video/*'})
    ) 

user/views.py
import json
import os
import re
from django.db import models
from django.db.models import query
from django.http.response import JsonResponse
import requests
import base64

from os import access, error
from django.db.models.expressions import F, Case, When
from django.db.models.fields import CharField
from django.db.models.query_utils import Q, FilteredRelation

from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.conf import settings
from requests.sessions import session
from bucket.settings import BASE_DIR, PROJECT_ROOT, ROOT_DIR
from user.social_login import callback

from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import action

from party.models import UserParty

from .forms import RegisterForm
from .forms import LoginForm, RegisterForm
from .models import Interest, User, UserInterest
from .forms import RegisterForm
from .serializer import InterestSerializer, UserInterestSerializer, UserSerializer
from .decorators import admin_required
from django.contrib.auth.hashers import make_password

# views.py
# 기존에 사용하던 메소드
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.hashers import check_password
from django.contrib.auth import get_user_model
from django.contrib import auth


# 새로 추가하는 메소드
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template, render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from email.utils import formataddr

# from email.message import EmailMessage
import smtplib

from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text

from email.utils import formataddr


class InterestViewSet(viewsets.ViewSet):
    def create(self, request):
        user_id = request.session.get("user")
        user = User.objects.filter(id=user_id).all()[0]
        interest = request.POST["interest"]
        current_interests = Interest.objects.filter(interest=interest).all()
        if current_interests:
            interest = current_interests[0]
        else:
            interest = Interest(interest=interest)
            interest.save()
        current_user_interest = UserInterest.objects.filter(
            user_id=user_id, interest_id=interest.id
        ).all()
        if current_user_interest:
            pass
        else:
            user_interest = UserInterest(user_id=user, interest_id=interest)
            user_interest.save()
        queryset = Interest.objects.all()
        serializer = InterestSerializer(queryset, many=True)
        # return Response(serializer.data)
        return redirect("user:profile")

    def list():
        return "test"


class UserInterestViewSet(viewsets.ModelViewSet):
    queryset = UserInterest.objects.all()
    serializer_class = UserInterestSerializer


def delete(request):
    user_interest_id = request.GET.get("user_interest_id")
    user_interest = UserInterest.objects.get(id=user_interest_id)
    interest = user_interest.interest_id

    user_interest.delete()
    interest.delete()

    result = {"msg": "good"}
    return JsonResponse(result)


def update(request):
    if request.POST.get("user_id"):
        user_id = request.POST.get("user_id")
    else:
        user_id = request.session.get("user")
    user = User.objects.get(id=user_id)
    if request.method == "POST":
        if request.FILES.get("image"):
            user.image = request.FILES.get("image")
        if request.POST.get("name"):
            user.name = request.POST.get("name")
        if request.POST.get("detail"):
            user.detail = request.POST.get("detail")
        if request.POST.get("instagram"):
            user.instagram = request.POST.get("instagram")
        if request.POST.get("password"):
            if request.POST.get("password") == request.POST.get("re_password"):
                user.password = make_password(request.POST.get("password"))
        user.save()
        return redirect("user:profile")


def profile(request):
    user_id = request.session.get("user")
    my = True
    if request.method == "GET":
        if request.GET.get("id"):
            user_id = request.GET.get("id")
            my = False
    try:
        user = User.objects.get(id=user_id)
    except:
        return redirect("user:login")
    user_interest = (
        UserInterest.objects.filter(user_id=user_id).select_related("interest_id").all()
    )
    user_party = (
        UserParty.objects.filter(user_id=user_id).select_related("party_id").all()
    )
    return render(
        request,
        "profile.html",
        {
            "user": user,
            "user_interest": user_interest,
            "user_party": user_party,
            "my": my,
        },
    )


def index(request):
    if request.session.get("user"):
        return redirect("user:profile")
    else:
        return redirect("user:login")


def logout(request):
    if "user" in request.session:
        del request.session["user"]
    return redirect("user:login")


def callback_social(request, type):

    # Get user information from callback function
    user_info = callback(request, type)
    print(user_info)

    # DB에서 중복여부 확인 후 유저 정보 저장
    try:
        user_in_db = User.objects.get(social_id=user_info["social_id"])
    except User.DoesNotExist:
        user_in_db = None
    if user_in_db:
        user = user_in_db
    else:
        user = User(
            name=user_info["name"],
            email=user_info["email"],
            password=None,
            social_login=type,
            social_id=user_info["social_id"],
        )
        user.save()

    # 소셜 로그인 후 홈페이지로 이동
    request.session["user"] = user.id
    return redirect("user:profile")


def login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            user = User.objects.get(email=email)
            if check_password(password, user.password):
                request.session["user"] = user.id
                return redirect("user:profile")
            else:
                error = "비밀번호를 확인해주세요."
                return render(request, "login.html", {"error": error})
        except Exception as e:
            print(e)
            error = "존재하지 않는 회원입니다."
            return render(request, "login.html", {"error": error})
    else:
        try:
            user = User.objects.get(id=request.session.get("user"))
        except:
            user = None
        return render(request, "login.html", {"user": user})


def find_password(request):
    if request.method == "POST":
        user_email = request.POST.get("email")

        try:
            user = User.objects.get(email=user_email)
        except:
            return render(request, "find_password.html", {"error": "존재하지 않는 이메일입니다."})
        print(user)
        message = render_to_string(
            "find_password_email.html",
            {
                "user": user,
                "domain": get_current_site(request).domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)).encode().decode(),
                "token": account_activation_token.make_token(user),
            },
        )
        mail_subject = "[버킷리스터] 비밀번호 초기화 메일입니다."

        email = EmailMessage(mail_subject, message, to=[user_email])
        email.send()

        return redirect("user:find_password")
    else:
        return render(request, "find_password.html")


def register(request):
    if request.method == "POST":
        if request.POST["password"] == request.POST["re_password"]:
            user = User(
                name=request.POST.get("name"),
                email=request.POST.get("email"),
                password=make_password(request.POST.get("password")),
                is_active=False,
            )
            if request.FILES.get("image"):
                user.image = request.FILES.get("image")
            user.save()
            message = render_to_string(
                "activate_email.html",
                {
                    "user": user,
                    "domain": get_current_site(request).domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk))
                    .encode()
                    .decode(),
                    "token": account_activation_token.make_token(user),
                },
            )
            mail_subject = "[버킷리스터] 회원가입 인증 메일입니다."
            user_email = user.email
            email = EmailMessage(mail_subject, message, to=[user_email])
            email.send()
            return redirect("user:profile")
    else:
        return render(request, "register.html")


def activate(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    try:
        user = User.objects.get(id=uid)
    except User.DoesNotExist:
        return HttpResponse("비정상적인 접근입니다.")

    if account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        request.session["user"] = uid
        return redirect("user:profile")


def reset_password(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    try:
        user = User.objects.get(id=uid)
    except User.DoesNotExist:
        return HttpResponse("비정상적인 접근입니다.")

    if account_activation_token.check_token(user, token):
        request.session["user"] = uid
        return render(request, "reset_password.html", {"user": user})


import os
from email.mime.image import MIMEImage

from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string


def send_mail_test():

    rendered_report = RenderedReport.objects.get(pk=1)

user/templates/activate_email.html
{% autoescape off %} 
안녕하세요 아래 링크를 클릭하면 회원가입 인증이 완료됩니다. 
회원가입 링크 : 
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %} 
{% endautoescape %}

user/templates/base.html
<html>

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <link rel="stylesheet" href="/static/css/main.css" />

    <link rel="shortcut icon" href="/static/images/favicon.ico">

    <title>Bucket Lister</title>

    {% block extrahead %}{% endblock %}
</head>

<body>
    {% block contents %} {% endblock %} 

    <script src="/static/js/csrf_token.js"></script>
    
    {% block extrascripts %} {% endblock %}
</body>

</html>

user/templates/find_password.html
{% extends 'base.html' %}

{% block contents %}
<div class="content">
    <section class="banner-main">
        <img class="banner-img" src="/static/images/loginpage.png" alt="" />
        <div class="login-wrap">

            <form id="findPasswordForm" action="/user/find_password/" method="post">
                {% csrf_token %}
                <input type="text" name="email" />
                {%if error%}
                <input type="text" value="{{error}}" readonly/>
                {%endif%}
                <button typ="submit" onclick="submit_form()">비밀번호 찾기</button>
            </form>

        </div>
    </section>
</div>
{%endblock%}

{% block extrascripts %}
<script>
    var form = document.getElementById('findPasswordForm');

    function submit_form() {
        if (form.checkValidity()) {
            alert("비밀번호 초기화를 위해 메일을 확인해주세요");
        }
    }
</script>
{% endblock %}

user/templates/find_password_email.html
{% autoescape off %} 
안녕하세요 아래 링크를 클릭하면 회원가입 인증이 완료됩니다.
회원가입 링크 : 
http://{{ domain }}{% url 'user:reset_password' uidb64=uid token=token %} 
{% endautoescape %}

user/templates/index.html
{% extends "base.html" %} {% block contents %}
<div class="content">
    <section class="banner-main">
        <img class="banner-img" src="/static/images/main.png" alt="" />
    </section>
</div>
{% endblock %}

user/templates/login.html
{% extends 'base.html' %} 

{% block contents %}
<div class="content">
  <section class="banner-main">
    <img class="banner-img" src="/static/images/loginpage.png" alt="" />
    <div class="login-wrap">
      
      {% if user.id %}
      <form action="/user/logout/" method="post">
        {% csrf_token %}
        <input type="text" value="{{user.email}}" readonly />
        <input type="submit" value="로그아웃" />
      </form>
      {% else %}
      <form action="/user/login/" method="post">
        {% csrf_token %}
        <input type="text" name="email" placeholder="이메일" />
        
        <input type="password" name="password" placeholder="비밀번호" />
        
        {% if error %}
        <h5 style="color:red">{{error}}</h5>
        {% endif %}

        <button type="submit" class="btn-login">로그인</button>
        <button type="button" onclick="location.href='/user/find_password'">비밀번호 찾기</button>
      </form>
      {% endif %}
      
      <button onclick="location.href='/user/register'">회원가입</button>
    </div>
  </section>
</div>
{%endblock%}

user/templates/profile copy.html
{% extends 'base.html' %}

{% block contents %}
<div class="content content--padding">
    <section class="profile">
        <div class="profile-box">

            <div class="profile-header">
                {% if my %}
                <h1>내 프로필</h1>
                <button onclick="location.href='/user/logout' "> 로그아웃</button>
                {%else%}
                <h1>{{user.name}}님의 프로필</h1>
                {%endif%}
            </div>


            <div class="profile-wrap">


                {# 프로필 사진 #}
                {%if my%}
                <div class="profile-img"
                    style="background-image: url('/media/{{user.image}}'); background-size: cover; background-repeat: no-repeat;"
                    onclick="open_image_input()">
                </div>
                <form action="/user/update/" id="imageForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="image" id="imageInput" style="display: none" />
                </form>
                {%else%}
                <div class="profile-img"
                    style="background-image: url('/media/{{user.image}}'); background-size: cover; background-repeat: no-repeat;">
                </div>
                {%endif%}

                <h3>
                    {{user.name}}
                    {%if my%}
                    <a class="open-input"><i class="fas fa-edit"></i></a>
                    {% endif %}

                    <br>

                    {%if user.instagram%}
                    <a href="https://www.instagram.com/{{user.instagram}}">
                        <i class="fab fa-instagram"></i> {{user.instagram}}
                    </a>
                    {%endif%}

                </h3>


            </div>

            {# 개인 정보 #}

            {%if my%}
            <form class="username-form" action="/user/update/" method="post">
                {%csrf_token%}
                <input type="text" name="name" value="{{user.name}}">

                {% if user.detail %}
                <input type="text" name="detail" value="{{user.detail}}">
                {% else %}
                <input type="text" name="detail" value="">
                {% endif %}

                {% if user.instagram %}
                <input type="text" name="instagram" placeholder="인스타그램 아이디" value="{{user.instagram}}">
                {% else %}
                <input type="text" name="instagram" placeholder="인스타그램 아이디" value="">
                {% endif %}

                <input type="submit" value="수정">
            </form>
            {%endif%}

            <div class="profile-description">
                {%if user.detail%}
                <p>{{user.detail}}</p>
                {%else%}
                <p>자기소개가 없습니다.</p>
                {%endif%}
            </div>


            {# 관심사 #}
            <div class="profile-tag">
                <form class="profile-tag-form" action="/api/interest/" , method="post">
                    <input type="text" name="interest" />
                    <input type="submit" value="관심사 추가하기 - 하나씩 추가해 주세요" />
                </form>
                {% for interest in user_interest %}
                <span>
                    #{{interest.interest_id.interest}}

                    {%if my%}
                    <a onclick="deleteTag(this, {{interest.id}} )"><i class="fas fa-times"></i></a>
                    {%endif%}
                </span>
                {% endfor %}
            </div>

            <div>
                {%if my and user.is_admin%}
                <button class="btn-manager" onclick="location.href='/manager'">관리자 페이지로 이동</button>
                {%endif%}
                <br>
                <button class="btn-manager" onclick="location.href='/party?filter=like' ">내가 찜한 소셜링</button>
                <button class="btn-manager" onclick="location.href='/party?filter=join' ">내가 참여한 소셜링</button>
            </div>

        </div>{#profile-box#}

        <img class="img-vertical" src="/static/images/logo_vertical.png" alt="" />
        <div class="bottom-nav">
            <a href="/party">
                <i class="fas fa-users"></i>
                <p>소셜링</p>
            </a>
            <a href="/party/create">
                <i class="fas fa-plus-circle"></i>
            </a>
            <a href="/user/profile">
                <i class="fas fa-user"></i>
                <p>프로필</p>
            </a>
        </div>
    </section>
</div>
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
    function open_image_input() {
        document.getElementById("imageInput").click();
    }

    imageInput.onchange = evt => {
        const [file] = imageInput.files
        if (file) {
            profileImage.src = URL.createObjectURL(file)
        }
    }

    $('#imageInput').on('change', function () {
        console.log($(this).val)
        $('#imageForm').submit();
    });

    $('.open-input').click(function () {
        $('.username-form').toggleClass('active');
        $('.profile-tag-form').toggleClass('active');
    });

    function deleteTag(element, user_interest_id) {
        console.log(user_interest_id)

        $.ajax({
            type: 'get',
            url: '/user/delete',
            data: {
                'user_interest_id': user_interest_id
            },
            dataType: 'json',
            success: function (result) {
                console.log("성공")
            }
        });
        element.parentNode.style.display = "none";
        console.log('태그 삭제');
    }
</script>
{% endblock %}

user/templates/profile.html
{% extends 'base.html' %}

{% block contents %}
<div class="content content--padding">
    <section class="profile">
        <div class="profile-box">

            <div class="profile-header">
                {% if my %}
                <h1>내 프로필</h1>
                <button onclick="location.href='/user/logout' "> 로그아웃</button>
                {%else%}
                <h1>{{user.name}}님의 프로필</h1>
                {%endif%}
            </div>


            <div class="profile-wrap">


                {# 프로필 사진 #}
                {%if my%}
                <div class="profile-img"
                    style="background-image: url('/media/{{user.image}}'); background-size: cover; background-repeat: no-repeat;"
                    onclick="open_image_input()">
                </div>
                <form action="/user/update/" id="imageForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="image" id="imageInput" style="display: none" />
                </form>
                {%else%}
                <div class="profile-img"
                    style="background-image: url('/media/{{user.image}}'); background-size: cover; background-repeat: no-repeat;">
                </div>
                {%endif%}

                <h3>
                    {{user.name}}
                    {%if my%}
                    <a class="open-input"><i class="fas fa-edit"></i></a>
                    {% endif %}

                    <br>

                    {%if user.instagram%}
                    <a href="https://www.instagram.com/{{user.instagram}}">
                        <i class="fab fa-instagram"></i> {{user.instagram}}
                    </a>
                    {%endif%}

                </h3>


            </div>

            {# 개인 정보 #}

            {%if my%}
            <form class="username-form" action="/user/update/" method="post">
                {%csrf_token%}
                <input type="text" name="name" value="{{user.name}}">

                {% if user.detail %}
                <input type="text" name="detail" value="{{user.detail}}">
                {% else %}
                <input type="text" name="detail" value="">
                {% endif %}

                {% if user.instagram %}
                <input type="text" name="instagram" placeholder="인스타그램 아이디" value="{{user.instagram}}">
                {% else %}
                <input type="text" name="instagram" placeholder="인스타그램 아이디" value="">
                {% endif %}

                <input type="submit" value="수정">
            </form>
            {%endif%}

            <div class="profile-description">
                {%if user.detail%}
                <p>{{user.detail}}</p>
                {%else%}
                <p>자기소개가 없습니다.</p>
                {%endif%}
            </div>


            {# 관심사 #}
            <div class="profile-tag">
                <form class="profile-tag-form" action="/api/interest/" , method="post">
                    <input type="text" name="interest" />
                    <input type="submit" value="관심사 추가하기 - 하나씩 추가해 주세요" />
                </form>
                {% for interest in user_interest %}
                <span>
                    #{{interest.interest_id.interest}}

                    {%if my%}
                    <a onclick="deleteTag(this, {{interest.id}} )"><i class="fas fa-times"></i></a>
                    {%endif%}
                </span>
                {% endfor %}
            </div>

            <div>
                {%if my and user.is_admin%}
                <button class="btn-manager" onclick="location.href='/manager'">관리자 페이지로 이동</button>
                {%endif%}
                <br>
                <button class="btn-manager" onclick="location.href='/party?filter=like' ">내가 찜한 소셜링</button>
                <button class="btn-manager" onclick="location.href='/party?filter=join' ">내가 참여한 소셜링</button>
            </div>

        </div>{#profile-box#}

        <img class="img-vertical" src="/static/images/logo_vertical.png" alt="" />
        <div class="bottom-nav">
            <a href="/party">
                <i class="fas fa-users"></i>
                <p>소셜링</p>
            </a>
            <a href="/party/create">
                <i class="fas fa-plus-circle"></i>
            </a>
            <a href="/user/profile">
                <i class="fas fa-user"></i>
                <p>프로필</p>
            </a>
        </div>
    </section>
</div>
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
    function open_image_input() {
        document.getElementById("imageInput").click();
    }

    imageInput.onchange = evt => {
        const [file] = imageInput.files
        if (file) {
            profileImage.src = URL.createObjectURL(file)
        }
    }

    $('#imageInput').on('change', function () {
        console.log($(this).val)
        $('#imageForm').submit();
    });

    $('.open-input').click(function () {
        $('.username-form').toggleClass('active');
        $('.profile-tag-form').toggleClass('active');
    });

    function deleteTag(element, user_interest_id) {
        console.log(user_interest_id)

        $.ajax({
            type: 'get',
            url: '/user/delete',
            data: {
                'user_interest_id': user_interest_id
            },
            dataType: 'json',
            success: function (result) {
                console.log("성공")
            }
        });
        element.parentNode.style.display = "none";
        console.log('태그 삭제');
    }
</script>
{% endblock %}